# Site settings
author: B to the I to the S
title: Hacking the Coding Boot Camp Model for Fun and Profit*
header-img: img/home-bg.png
email: age.ef.ess@gmail.com
copyright_name: B to the I to the S
description: > # this means to ignore newlines until "baseurl:"
  Forgo Career Help & Instead Make Software to Crush the Competition
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  operacyloop

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
